# Generated by Django 2.0.7 on 2018-07-31 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bovespa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ticker', models.CharField(max_length=7)),
                ('Date', models.DateField()),
                ('Open', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('High', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('Low', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('Close', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('Volume', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TICKER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ticker', models.CharField(max_length=7)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='bovespa',
            unique_together={('Ticker', 'Date')},
        ),
    ]
